version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_container
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
