version: '3.1'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: my_postgres_container
    deploy:
      resources:
        limits:
          cpus: '0.5'
          # mem_limit: ""
          memory: '0.5g'
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  scrapper_zameen:
    image: scrapper_zameen_image
    build:
      context: .
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1g'
        reservations:
          memory: '0.3g'
    container_name: scrapper_zameen_container
    tty: true
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - postgres
volumes:
  postgres_data:
